FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /src/kubevirt-csi-driver
COPY . .
RUN make build

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9

LABEL io.openshift.release.operator=true
LABEL description="KubeVirt CSI Driver"

RUN yum install -y e2fsprogs xfsprogs && yum clean all
COPY --from=builder /src/kubevirt-csi-driver/kubevirt-csi-driver .

ENTRYPOINT ["./kubevirt-csi-driver"]
